name: Maven CI/CD

on:
 push:
    branches: [ master ]
  

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    
    - name: Deploy to CloudHub
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy -Dusername=${{ secrets.cloudhub_username}} -Dpassword=${{ secrets.cloudhub_password }} -Denvironment=${{ secrets.dev_environment }} -DapplicationName=${{ secrets.dev_application_name }} -DworkerType=${{ secrets.worker_type }}
    

