# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: uat in master branch

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Cloudhub deployment
      run: mvn deploy -DmuleDeploy -Dusername=${{ secrets.cloudhub_username}} -Dpassword=${{ secrets.cloudhub_password }} -Denvironment=${{ secrets.dev_environment }} -DapplicationName=${{ secrets.dev_application_name }} -DworkerType=${{ secrets.worker_type }}
